TaskManager/force-app/main/default/objects/Assigned_task__c/Assigned_task__c.object-meta.xml
<CustomObject>
    <label>Assigned task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Task_status__c.field-meta.xml
<CustomField>
    <fullName>Task_status__c</fullName>
    <label>Task Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>To Be Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/classes/PreventEditOnCompletionTest.cls
@isTest
public class PreventEditOnCompletionTest {
    @isTest static void TestPreventEditOnCompletion() {
        Assigned_task__c[] tasks= AssignedTaskTestDataFactory.createtasks(1);
        insert(tasks);
        for(Assigned_task__c t: tasks){
            t.Task_status__c= 'Completed';
        }
        Test.startTest();
        for(Assigned_task__c t: tasks){
            t.Name= 'Test for trigger';
        }
        Database.SaveResult result = Database.update(tasks[0],false);
        Test.stopTest();
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('Cannot edit on completed task.',
                            result.getErrors()[0].getMessage());
    }  
}