TaskManager/force-app/main/default/objects/Assigned_task__c/Assigned_task__c.object-meta.xml
<CustomObject>
    <label>Assigned task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unapproved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/classes/NewTaskTest.cls
@isTest
public class NewTaskTest {
    @isTest static void TestSetApprovalStatus() {
        Assigned_task__c[] tasks= AssignedTaskTestDataFactory.createtasks(1);
        Test.startTest();
        Database.SaveResult result = Database.insert(tasks[0], false);
        Test.stopTest();
        System.assert(result.isSuccess());
        List<Assigned_task__c> taskList= [Select Approval_Status__c from Assigned_task__c Where Id= :tasks[0].Id];
        for(Assigned_task__c t: taskList){
            system.assertEquals('Unapproved', t.Approval_Status__c);
        }
    }     
    
      @isTest static void TestBulkSetApprovalStatus() {
        Assigned_task__c[] tasks= AssignedTaskTestDataFactory.createtasks(200);
        Test.startTest();
        Database.SaveResult[] results = Database.insert(tasks, false);
        Test.stopTest();
          
        for(Database.SaveResult dr : results) {
            System.assert(dr.isSuccess());
        }
        List<Assigned_task__c> taskList= [Select Approval_Status__c from Assigned_task__c Where Id= :tasks];
        for(Assigned_task__c t: taskList){
            system.assertEquals('Unpproved', t.Approval_Status__c);
        }
    }     
}