TaskManager/force-app/main/default/objects/Assigned_task__c/Assigned_task__c.object-meta.xml
<CustomObject>
    <label>Assigned task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Task_status__c.field-meta.xml
<CustomField>
    <fullName>Task_status__c</fullName>
    <label>Task Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>To Be Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/objects/Personal_Task__c/Personal_Task__c.object-meta.xml
<CustomObject>
    <label>Personal Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/objects/Personal_Task__c/fields/Task_Status__c.field-meta.xml
<CustomField>
    <fullName>Task_Status__c</fullName>
    <label>Task Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not_Started</fullName>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In_Progress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/classes/getTaskController.cls
public with sharing class getTaskController {
@AuraEnabled(cacheable=true)
public static List<Personal_Task__c> getTasks() {
return [SELECT Id, Name, Description__c, Task_status__c,Priority__c FROM Personal_Task__c];
}

@AuraEnabled(cacheable=true)
public static List<Assigned_Task__c> getUrgentTasks() {
return [SELECT Id, Name, Priority__c FROM Assigned_Task__c Where Task_status__c ='In Progress'
        AND Priority__c = 'High'];
}


@AuraEnabled
public static void deletePersonalTask(Id ptId) {
Personal_Task__c personalTask = new  Personal_Task__c();
personalTask = [SELECT Id FROM Personal_Task__c Where Id= :ptId];
delete(personalTask);
}
}