TaskManager/force-app/main/default/objects/Assigned_task__c/Assigned_task__c.object-meta.xml
<CustomObject>
    <label>Assigned task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unapproved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Task_status__c.field-meta.xml
<CustomField>
    <fullName>Task_status__c</fullName>
    <label>Task Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>To Be Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/classes/SetPendingTest.cls
@isTest public class SetPendingTest {
    
    @isTest static void TestSetPendingCompleteAndUnapproved() {
        Assigned_task__c[] tasks= AssignedTaskTestDataFactory.createtasks(1);
        insert(tasks);
        Test.startTest();
        for(Assigned_task__c t: tasks){
            t.Task_status__c= 'Completed';
        }
        Database.SaveResult result = Database.update(tasks[0],false);
        Test.stopTest();
        System.assert(result.isSuccess());
        List<Assigned_task__c> taskList= [Select Approval_Status__c from Assigned_task__c Where Id= :tasks];
        for(Assigned_task__c t: taskList){
            system.assertEquals('Pending', t.Approval_Status__c);
        }
    }     
    @isTest static void TestBulkSetPendingCompleteAndUnapproved() {
        Assigned_task__c[] tasks= AssignedTaskTestDataFactory.createtasks(200);
        insert(tasks);
        Test.startTest();
        for(Assigned_task__c t: tasks){
            t.Task_status__c= 'Completed';
        }
        Database.SaveResult[] results = Database.update(tasks,false);
        Test.stopTest();
        for(Database.SaveResult dr : results) {
            System.assert(dr.isSuccess());
        }
        List<Assigned_task__c> taskList= [Select Approval_Status__c from Assigned_task__c Where Id= :tasks];
        for(Assigned_task__c t: taskList){
            system.assertEquals('Pending', t.Approval_Status__c);
        }
    }     
    
    
}