TaskManager/force-app/main/default/objects/Assigned_task__c/Assigned_task__c.object-meta.xml
<CustomObject>
    <label>Assigned task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unapproved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assigned tasks</relationshipLabel>
    <relationshipName>Assigned_tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/Task_status__c.field-meta.xml
<CustomField>
    <fullName>Task_status__c</fullName>
    <label>Task Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>To Be Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TaskManager/force-app/main/default/objects/Assigned_task__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Developer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

TaskManager/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TaskManager/force-app/main/default/classes/Task_TableController.cls
public class Task_TableController {
    @AuraEnabled
    public static List<Assigned_task__c> getTasks(id pId) {
        List<Assigned_task__c> tasks = 
            [SELECT  Name, User__r.username, user__r.firstname,user__r.lastname , Task_status__c, Priority__c,Approval_status__c FROM Assigned_task__c 
             Where Project__c = :pID];
        //Add isAccessible() check
        return tasks;
    }
    
     @AuraEnabled
    public static List<Assigned_task__c> getSupervisor(id pId) {
        List<Assigned_task__c> supervisor = 
            [SELECT  CreatedById FROM Assigned_task__c 
             Where Project__c = :pID];
        //Add isAccessible() check
        return supervisor;
    }
    
    
    @AuraEnabled
    public static List<Wrapper> getUserValueWrapper(Id pId) {
        //
        Map<String,Integer> userValues = new Map<String,Integer>();
        List<Wrapper> wrapperlist = new List<Wrapper>();
        List<Integer> countTask = new List<Integer>();
        List<Integer> countAllTask = new List<Integer>();
        List<String> userName = new List<String>();
        List<String> fullName = new List<String>();
        // List<Wrapper> userWrapper = new List<Wrapper>();
        string check;
        
        AggregateResult[]  allTasks = [SELECT User__r.firstName, User__r.LastName,User__r.username,COUNT(Name) FROM Assigned_task__c  Where Project__c = :pID Group By User__r.username, User__r.firstName, User__r.Lastname];
        AggregateResult[]  completedTask = [SELECT User__r.firstName, User__r.LastName,User__r.username,COUNT(Name) FROM Assigned_task__c where Task_status__c = 'completed' AND  Project__c = :pID Group By User__r.username, User__r.firstName, User__r.Lastname];
        
        for (AggregateResult result:allTasks){
            username.add((String)result.get('UserName'));
            fullName.add((String)result.get('FirstName')+' '+(String)result.get('LastName')); 
            countAllTask.add((Integer)result.get('expr0'));
        }
        for (AggregateResult completeResult:completedTask){  
            check= (String)completeResult.get('UserName');
            userValues.put(check,(Integer)completeResult.get('expr0'));
        }
        for(integer i=0; i<userName.size(); i++){
            if(check.contains(userName[i]))
            {countTask.add(userValues.get(userName[i]));
            }
            else{countTask.add(0);}
        }
        
        for(integer i = 0; i<fullName.size();i++)
        {
            Wrapper mywrapper= new Wrapper(fullName[i],userName[i],countTask[i],countAllTask[i]);
            wrapperlist.add(mywrapper);
        }
        System.debug(wrapperlist);
        //userWrapper.add(wrapperlist);
        return wrapperlist;
    }
    
    
    public class Wrapper{
        @AuraEnabled
        public String fullName {get;set;}
        @AuraEnabled
        public String userName {get;set;}
        @AuraEnabled
        public Integer countTask {get;set;}   
        @AuraEnabled
        public Integer countAllTask {get;set;}
        public Wrapper(String fullName,String userName,Integer countTask,Integer countAllTask)
        {
            this.fullName= fullName;
            this.userName= userName;
            this.countTask= countTask;
            this.countAllTask= countAllTask;
        }
    }
    
    
    @AuraEnabled
    public static void deleteTask(string getId) {
        delete [select Id FROM Assigned_task__c where Id=:getId];
    }
}